version: "3"

services:
  jupyter:
    build:
      context: notebook-docker
      dockerfile: Dockerfile
    image: jyp-notebook:v1
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./notebook-docker:/home/jovyan/work/build
      - ./data:/home/jovyan/work/data
      - ./src:/home/jovyan/work/src
    ports:
      - 8888:8888
    links:
      - db

  db:
    image: postgres:12
    restart: always
    env_file:
      - src/database.env
    volumes:
      - ./scripts/init:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:

# TODO: add python container for init_db
# TODO: add ALS model and reranking model